name: Ubuntu

on:
  push:
  pull_request:

jobs:

  sciunit-test-ubuntu-22-04-with-tox:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: install-packages  
          run: sudo apt-get install -y software-properties-common g++-9
        - name: add-apt-repository
          run: sudo add-apt-repository ppa:deadsnakes/ppa
        - name: install-python3  
          run: sudo apt-get update && sudo apt-get install -y python3.8 python3.8-dev python3.8-distutils
        - name: update-pip
          run: pip3 install --upgrade pip
        - name: check-compiler
          run: which g++-9
        - name: set-compiler-g++-9
          run: export CMAKE_CXX_COMPILER=/usr/bin/g++-9
        - name: set-ld-flag
          run: export LDFLAGs="-Wl,--allow-multiple-definition"
        - name: install-tox
          run: pip3 install tox
        - name: test-with-tox
          run: tox

  sciunit-test-ubuntu-20-04-with-tox:
      runs-on: ubuntu-latest
      container: geotrust/build-essential:ubuntu20.04
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: update-pip
          run: pip3 install --upgrade pip
        - name: install-tox
          run: pip3 install tox
        - name: test-with-tox
          run: tox

  sciunit-test-ubuntu-16-04-with-tox:
      runs-on: ubuntu-latest
      container: geotrust/build-essential:ubuntu16.04
      steps:
        - name: install-https
          run:  apt-get update && apt install apt-transport-https
        - name: update-git
          run:  echo "deb https://ppa.launchpadcontent.net/git-core/ppa/ubuntu xenial main" >> /etc/apt/sources.list
        - name: install-key
          run: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
        - name: install  
          run: apt-get update && apt-get install git -y
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: git-config
          run: git config --global --add safe.directory /__w/sciunit/sciunit
        - name: update-pip
          run: pip3 install --upgrade pip
        - name: install-tox
          run: pip3 install tox
        - name: test-with-tox
          run: tox -e py37
